---
title: Publang
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: publang.team@gmail.com
description: Webtoon Localization Team·웹툰 현지화 팀 | Bridging people with words and pixels
  | 문자와 픽셀로 사람을 연결합니다
baseurl: 
url: 
twitter_username: publang
github_username: publang
theme: minima
plugins:
- jekyll-feed
