---
title: Publang
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: article
    sharing: true
    license: true
    aside:
      toc: true
    show_edit_on_github: true
    show_subscribe: true
    pageview: true
text_skin: default
highlight_theme: default
url: 
baseurl: 
description: 'Webtoon Localization Team·웹툰 현지화 팀 | Bridging people with words and pixels | 문자와 픽셀로 사람을 연결합니다'
lang: en
author:
  type: organization
  name: Publang
  url: 
  avatar: "./asset/images/publang-background.png"
  bio: I am an amazing person.
  email: publang.team@gmail.com
  facebook: 
  twitter: publang
  weibo: 
  googleplus: 
  telegram: 
  medium: 
  zhihu: 
  douban: 
  linkedin: 
  github: 
  npm: 
repository: publang/puglang.github.io
repository_tree: main
paths:
  root: 
  home: 
  rss: 
excerpt_separator: "<!--more-->"
license: CC-BY-NC-4.0
toc:
  selectors: 
mathjax: 
mathjax_autoNumber: 
mermaid: 
chart: 
paginate: 8
paginate_path: "/page:num"
sources: 
sharing:
  provider: false
  addthis:
    id: 
comments:
  provider: false
  disqus:
    shortname: 
  gitalk:
    clientID: 
    clientSecret: 
    repository: 
    owner: 
    admin: 
  valine:
    app_id: 
    app_key: 
    placeholder: 
    visitor: 
    meta: 
pageview:
  provider: false
  leancloud:
    app_id: 
    app_key: 
    app_class: 
search:
  provider: default
  google:
    custom_search_engine_id: 
analytics:
  provider: false
  google:
    tracking_id: G-QCREZVCKD4
    anonymize_ip: false
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
- CHANGELOG.md
- HOW_TO_RELEASE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- "/docs"
- "/node_modules"
- "/screenshots"
- "/test"
- "/vendor"
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji
